### ISSUE TITLE
Works only locally

### ISSUE THREAD

**Issue by gongzhitaao** [L3au/gitbook-plugin-git-author#1]
Hi,
Thanks for this plugin.  It is wired that it works only locally (`gitbook serve .`). When I upload it to gitbook server, no author is shown.  Any idea this might happen?

**Comment by L3au** [comment]
This plugin fetch `git logs` of a file to show the author, sadly https://www.gitbook.com/ doesn't allow to execute `git` command in their server.

You can use https://pages.github.com/ to serve your project, just build locally and push `_book` directory to `gh-pages` branch.
