### ISSUE TITLE
Plugin is not working

### ISSUE THREAD

**Issue by sta-szek** [L3au/gitbook-plugin-git-author#4]
My books.json is:

```
{
  "plugins" : ["anchors",
               "toggle-chapters",
               "sitemap", 
               "nocache", 
               "back-to-top-button",
               "git-author",
               "advanced-emoji",
               "ga",
               "github"],
  "pluginsConfig": {
      "git-author": {
          "position": "bottom",
          "modifyTpl": "Last modified by {user} {timeStamp}",
          "createTpl": "Created by {user} {timeStamp}",
          "timeStampFormat": "YYYY-MM-DD HH:mm:ss"
      },
      "ga": {
          "token": "XXXX"
      },
      "sitemap": {
          "hostname": "https://pojo.pl/"
      },
      "github": {
          "url": "https://github.com/sta-szek/pojo-tester"
      }
  }
}
```

CSS is present on page:
![image](https://cloud.githubusercontent.com/assets/6240704/18810069/ee6bb40e-828c-11e6-964d-01f5274d8363.png)

But JS not:
![image](https://cloud.githubusercontent.com/assets/6240704/18810077/0d61f850-828d-11e6-91de-0245e4e11c1d.png)

Is my configuration wrong?

There is no author div on page

**Comment by L3au** [comment]
There is no js file. 

You need manage your project with `git` and commit at least once, then author div will be created in gitbook build.

**Comment by sta-szek** [comment]
Yeah I was newbie with plugins. I build book locally and it worked.
